spring:
  application:
    name: happymall
  datasource:
    url: jdbc:mysql://localhost:3306/happymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: /mapper/**.xml
  type-aliases-package: com.mooc.happymall.pojo,com.mooc.happymall.vo
    